import { describe, it, expect, vi, beforeEach } from "vitest";

const mockPrisma = {
  payment: { findMany: vi.fn() },
  church: { findUnique: vi.fn() },
  donor: { findMany: vi.fn() },
  givingLink: { findMany: vi.fn() },
  user: { findMany: vi.fn() },
  finixTransfer: { findMany: vi.fn() },
  finixPaymentInstrumentSnapshot: { findMany: vi.fn() },
  finixRefundOrReversal: { findMany: vi.fn() },
  finixDispute: { findMany: vi.fn() },
  bankReturn: { findMany: vi.fn() },
  finixSettlement: { findMany: vi.fn() },
  finixFundingTransferAttempt: { findMany: vi.fn() },
};
vi.mock("@/lib/prisma", () => ({ prisma: mockPrisma }));

async function loadModule() {
  vi.resetModules();
  return import("@/lib/exports/transactionExport");
}

beforeEach(() => {
  vi.clearAllMocks();
  for (const model of Object.values(mockPrisma)) {
    for (const fn of Object.values(model)) {
      (fn as any).mockResolvedValue(fn === mockPrisma.church.findUnique ? null : []);
    }
  }
});

const CANONICAL_HEADERS = [
  "Report Type", "Report Scope", "Report Owner Name", "Report Owner Email", "Report Owner User ID", "Report Owner Role",
  "Generated By Name", "Generated By Email", "Generated At", "Reporting Period Start", "Reporting Period End", "Applied Filters",
  "Organization Name", "Organization ID", "Team Member Name", "Team Member Email", "Giving Link Name", "Giving Link ID",
  "WGC Payment ID", "Processor Transaction ID", "Created At", "Currency", "Donor Name", "Donor Email", "Donor Phone",
  "Payment Method", "Instrument Type", "Card Brand or Bank Type", "Last Four", "Transaction Status", "Refund Status",
  "Dispute Status", "ACH Return Status", "Donation Amount", "Donor Processing Fee", "Total Charged to Donor",
  "Processor Fee", "WGC Supplemental Fee", "Other Processor Fees", "Total Fees", "Refund Amount", "Dispute Amount",
  "ACH Return Amount", "Expected Net to Organization", "Actual Net to Organization", "Settlement Included?",
  "Settlement Allocation Amount", "Settlement ID", "Settlement Status", "Settlement Created At", "Settlement Processed At",
  "Deposit or Funding Transfer ID", "Deposit Status", "Deposit Initiated At", "Deposit Completed At",
  "Destination Bank Last Four", "Trace ID", "Reconciliation Status", "Data Notes",
];

describe("TRANSACTION_EXPORT_COLUMNS", () => {
  it("matches the exact canonical column order", async () => {
    const { TRANSACTION_EXPORT_COLUMNS } = await loadModule();
    expect(TRANSACTION_EXPORT_COLUMNS.map((c) => c.header)).toEqual(CANONICAL_HEADERS);
  });

  it("never includes a full card/bank number, routing number, CVV, or token/credential column", async () => {
    const { TRANSACTION_EXPORT_COLUMNS } = await loadModule();
    const headers = TRANSACTION_EXPORT_COLUMNS.map((c) => c.header.toLowerCase());
    for (const forbidden of ["card number", "account number", "routing", "cvv", "token", "credential", "password", "secret"]) {
      expect(headers.some((h) => h.includes(forbidden))).toBe(false);
    }
  });
});

describe("formatMoneyOrEmpty", () => {
  it("formats cents as a plain two-decimal string with no currency symbol or thousands separator", async () => {
    const { formatMoneyOrEmpty } = await loadModule();
    expect(formatMoneyOrEmpty(5150)).toBe("51.50");
    expect(formatMoneyOrEmpty(0)).toBe("0.00");
    expect(formatMoneyOrEmpty(252526)).toBe("2525.26");
    expect(formatMoneyOrEmpty(5150)).not.toMatch(/[$,]/);
  });

  it("returns empty string (not 0.00) for null/undefined — unknown is not the same as zero", async () => {
    const { formatMoneyOrEmpty } = await loadModule();
    expect(formatMoneyOrEmpty(null)).toBe("");
    expect(formatMoneyOrEmpty(undefined)).toBe("");
  });
});

describe("normalizePaymentMethod", () => {
  it("normalizes raw Payment.paymentMethodType values to the canonical set", async () => {
    const { normalizePaymentMethod } = await loadModule();
    expect(normalizePaymentMethod("PAYMENT_CARD")).toBe("CARD");
    expect(normalizePaymentMethod("BANK_ACCOUNT")).toBe("ACH");
    expect(normalizePaymentMethod("APPLE_PAY")).toBe("APPLE_PAY");
    expect(normalizePaymentMethod("GOOGLE_PAY")).toBe("GOOGLE_PAY");
    expect(normalizePaymentMethod(null)).toBe("UNKNOWN");
  });
});

describe("normalizeTransactionStatus", () => {
  it("normalizes raw status values, defaulting unknowns to UNKNOWN (never blank = success)", async () => {
    const { normalizeTransactionStatus } = await loadModule();
    expect(normalizeTransactionStatus("SUCCEEDED")).toBe("SUCCEEDED");
    expect(normalizeTransactionStatus("pending")).toBe("PENDING");
    expect(normalizeTransactionStatus("CANCELLED")).toBe("CANCELED");
    expect(normalizeTransactionStatus(null)).toBe("UNKNOWN");
    expect(normalizeTransactionStatus("")).toBe("UNKNOWN");
  });
});

describe("normalizeRefundStatus", () => {
  it("counts only SUCCEEDED refunds toward the refunded amount", async () => {
    const { normalizeRefundStatus } = await loadModule();
    const result = normalizeRefundStatus(5000, [
      { amountCents: 5000, state: "SUCCEEDED" },
      { amountCents: 5000, state: "FAILED" },
      { amountCents: 5000, state: "CANCELED" },
    ]);
    expect(result.status).toBe("REFUNDED");
    expect(result.refundedCents).toBe(5000);
  });

  it("PARTIALLY_REFUNDED when succeeded refunds are less than the payment amount", async () => {
    const { normalizeRefundStatus } = await loadModule();
    const result = normalizeRefundStatus(5000, [{ amountCents: 2000, state: "SUCCEEDED" }]);
    expect(result.status).toBe("PARTIALLY_REFUNDED");
    expect(result.refundedCents).toBe(2000);
  });

  it("PENDING when a refund exists but hasn't succeeded, REFUND_FAILED when it failed outright", async () => {
    const { normalizeRefundStatus } = await loadModule();
    expect(normalizeRefundStatus(5000, [{ amountCents: 5000, state: "PENDING" }]).status).toBe("PENDING");
    expect(normalizeRefundStatus(5000, [{ amountCents: 5000, state: "FAILED" }]).status).toBe("REFUND_FAILED");
  });

  it("NONE when there are no refunds at all", async () => {
    const { normalizeRefundStatus } = await loadModule();
    expect(normalizeRefundStatus(5000, []).status).toBe("NONE");
  });
});

describe("resolveDisputeAmountCents", () => {
  it("WON disputes hold nothing against the organization", async () => {
    const { resolveDisputeAmountCents } = await loadModule();
    expect(resolveDisputeAmountCents({ amountCents: 5000, processorState: "WON", evidenceDueAt: null, respondedAt: null, resolvedAt: new Date(), outcome: "WON" })).toBe(0);
  });

  it("an open/unresolved dispute counts its full amount as held", async () => {
    const { resolveDisputeAmountCents } = await loadModule();
    expect(resolveDisputeAmountCents({ amountCents: 5000, processorState: "PENDING", evidenceDueAt: null, respondedAt: null, resolvedAt: null, outcome: null })).toBe(5000);
  });

  it("no dispute at all is zero", async () => {
    const { resolveDisputeAmountCents } = await loadModule();
    expect(resolveDisputeAmountCents(null)).toBe(0);
  });
});

describe("resolveTransactionExportRows", () => {
  const metadata = {
    reportType: "Organization Transaction Report",
    reportScope: "ENTIRE_ORGANIZATION",
    ownerName: "Entire Organization",
    ownerEmail: "",
    ownerUserId: "",
    ownerRole: "",
    generatedByName: "owner@x.com",
    generatedByEmail: "owner@x.com",
    generatedAt: new Date("2026-07-19"),
    periodStart: null,
    periodEnd: null,
    appliedFilters: "None",
  };

  it("organization scope (no attributedUserId filter) includes every authorized payment", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: "u1", givingLinkId: null, donorId: null, finixTransferId: null, paymentMethodType: "PAYMENT_CARD", amountCents: 1000, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: null, feeCoveredCents: null, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
      { id: "p2", churchId: "c1", attributedUserId: "u2", givingLinkId: null, donorId: null, finixTransferId: null, paymentMethodType: "PAYMENT_CARD", amountCents: 2000, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: null, feeCoveredCents: null, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });

    const { resolveTransactionExportRows } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    expect(mockPrisma.payment.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { churchId: "c1" } }));
    expect(rows).toHaveLength(2);
  });

  it("team-member scope filters strictly by Payment.attributedUserId, excluding other members' payments", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([]);
    const { resolveTransactionExportRows } = await loadModule();
    await resolveTransactionExportRows({ churchId: "c1", attributedUserId: "u1" }, metadata);
    expect(mockPrisma.payment.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { churchId: "c1", attributedUserId: "u1" } }));
  });

  it("giving-link scope filters strictly by Payment.givingLinkId", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([]);
    const { resolveTransactionExportRows } = await loadModule();
    await resolveTransactionExportRows({ churchId: "c1", givingLinkId: "link-1" }, metadata);
    expect(mockPrisma.payment.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { churchId: "c1", givingLinkId: "link-1" } }));
  });

  it("unattributed payments leave Team Member Name/Email empty rather than assigning the primary owner", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: null, givingLinkId: null, donorId: null, finixTransferId: null, paymentMethodType: "PAYMENT_CARD", amountCents: 1000, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: null, feeCoveredCents: null, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });

    const { resolveTransactionExportRows } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    expect(rows[0].teamMemberName).toBe("");
    expect(rows[0].teamMemberEmail).toBe("");
    expect(mockPrisma.user.findMany).not.toHaveBeenCalled(); // no attributed user ids to even look up
  });

  it("uses the actual Finix fee when available, never the pre-transaction estimate", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: null, givingLinkId: null, donorId: null, finixTransferId: "tr-1", paymentMethodType: "PAYMENT_CARD", amountCents: 1000, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: null, feeCoveredCents: null, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });
    mockPrisma.finixTransfer.findMany.mockResolvedValue([{ finixTransferId: "tr-1", feeCents: 87, finixSettlementId: null, finixPaymentInstrumentId: null }]);

    const { resolveTransactionExportRows } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    expect(rows[0].finixProcessingFeeCents).toBe(87);
  });

  it("leaves the Finix fee empty (not 0.00) when the actual fee hasn't been reconciled yet", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: null, givingLinkId: null, donorId: null, finixTransferId: "tr-1", paymentMethodType: "PAYMENT_CARD", amountCents: 1000, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: null, feeCoveredCents: null, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });
    mockPrisma.finixTransfer.findMany.mockResolvedValue([{ finixTransferId: "tr-1", feeCents: null, finixSettlementId: null, finixPaymentInstrumentId: null }]);

    const { resolveTransactionExportRows, formatMoneyOrEmpty } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    expect(rows[0].finixProcessingFeeCents).toBeNull();
    expect(rows[0].actualNetToOrganizationCents).toBeNull();
    expect(formatMoneyOrEmpty(rows[0].finixProcessingFeeCents)).toBe("");
  });

  it("separates the donor-covered fee from the donation amount and computes Total Charged to Donor correctly", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: null, givingLinkId: null, donorId: null, finixTransferId: null, paymentMethodType: "PAYMENT_CARD", amountCents: 5150, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: 5000, feeCoveredCents: 150, donorCoversFee: true, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });

    const { resolveTransactionExportRows } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    expect(rows[0].donationAmountCents).toBe(5000);
    expect(rows[0].donorProcessingFeeCents).toBe(150);
    expect(rows[0].totalChargedToDonorCents).toBe(5150);
  });

  it("Donor Processing Fee is 0 when the donor did not cover the fee, even if feeCoveredCents is set", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: null, givingLinkId: null, donorId: null, finixTransferId: null, paymentMethodType: "PAYMENT_CARD", amountCents: 5000, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: 5000, feeCoveredCents: 150, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });

    const { resolveTransactionExportRows } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    expect(rows[0].donorProcessingFeeCents).toBe(0);
  });

  it("Total Fees does not double-count — sums Finix + WGC supplemental + other exactly once each", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: null, givingLinkId: null, donorId: null, finixTransferId: "tr-1", paymentMethodType: "PAYMENT_CARD", amountCents: 1000, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: null, feeCoveredCents: null, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });
    mockPrisma.finixTransfer.findMany.mockResolvedValue([{ finixTransferId: "tr-1", feeCents: 87, finixSettlementId: null, finixPaymentInstrumentId: null }]);

    const { resolveTransactionExportRows } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    // WGC Supplemental Fee and Other Processor Fees are both 0/null in the
    // current data model — Total Fees must equal the Finix fee alone, not
    // some multiple of it.
    expect(rows[0].totalFeesCents).toBe(87);
  });

  it("a payment with no linked Finix transfer is never assigned a fabricated settlement — Settlement Included = NO, no Settlement ID", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: null, givingLinkId: null, donorId: null, finixTransferId: null, paymentMethodType: "PAYMENT_CARD", amountCents: 1000, status: "PENDING", createdAt: new Date(), donationAmountCents: null, feeCoveredCents: null, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });

    const { resolveTransactionExportRows } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    expect(rows[0].settlementIncluded).toBe("NO");
    expect(rows[0].settlementId).toBe("");
    expect(rows[0].settlementAllocationAmountCents).toBeNull();
    expect(rows[0].reconciliationStatus).toBe("NOT_SETTLED");
  });

  it("settlement linkage uses the authoritative FinixTransfer -> FinixSettlement chain, never a last-four/date heuristic", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: null, givingLinkId: null, donorId: null, finixTransferId: "tr-1", paymentMethodType: "PAYMENT_CARD", amountCents: 1000, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: null, feeCoveredCents: null, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });
    mockPrisma.finixTransfer.findMany.mockResolvedValue([{ finixTransferId: "tr-1", feeCents: 87, finixSettlementId: "stl-1", finixPaymentInstrumentId: null }]);
    mockPrisma.finixSettlement.findMany.mockResolvedValue([{ finixSettlementId: "stl-1", state: "SETTLED", createdAtFinix: new Date("2026-01-01"), settledAt: new Date("2026-01-03") }]);

    const { resolveTransactionExportRows } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    expect(mockPrisma.finixSettlement.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { finixSettlementId: { in: ["stl-1"] } } }));
    expect(rows[0].settlementIncluded).toBe("YES");
    expect(rows[0].settlementId).toBe("stl-1");
    expect(rows[0].settlementProcessedAt).toEqual(new Date("2026-01-03"));
  });

  it("deposit initiated/completed dates and masked destination account are exported", async () => {
    mockPrisma.payment.findMany.mockResolvedValue([
      { id: "p1", churchId: "c1", attributedUserId: null, givingLinkId: null, donorId: null, finixTransferId: "tr-1", paymentMethodType: "PAYMENT_CARD", amountCents: 1000, status: "SUCCEEDED", createdAt: new Date(), donationAmountCents: null, feeCoveredCents: null, donorCoversFee: false, merchantExpectedNetCents: null, currency: "USD" },
    ]);
    mockPrisma.church.findUnique.mockResolvedValue({ id: "c1", name: "Test Church" });
    mockPrisma.finixTransfer.findMany.mockResolvedValue([{ finixTransferId: "tr-1", feeCents: 87, finixSettlementId: "stl-1", finixPaymentInstrumentId: null }]);
    mockPrisma.finixSettlement.findMany.mockResolvedValue([{ finixSettlementId: "stl-1", state: "SETTLED", createdAtFinix: new Date("2026-01-01"), settledAt: new Date("2026-01-03") }]);
    mockPrisma.finixFundingTransferAttempt.findMany.mockResolvedValue([
      { finixFundingTransferAttemptId: "fta-1", finixSettlementId: "stl-1", state: "PAID", sentAt: new Date("2026-01-04"), arrivedAt: new Date("2026-01-05"), bankAccountLast4: "4321", traceId: "trace-abc" },
    ]);

    const { resolveTransactionExportRows } = await loadModule();
    const rows = await resolveTransactionExportRows({ churchId: "c1" }, metadata);
    expect(rows[0].depositId).toBe("fta-1");
    expect(rows[0].depositInitiatedAt).toEqual(new Date("2026-01-04"));
    expect(rows[0].depositCompletedAt).toEqual(new Date("2026-01-05"));
    expect(rows[0].destinationBankLastFour).toBe("4321");
    expect(rows[0].traceId).toBe("trace-abc");
  });
});

describe("renderTransactionCsv / CSV escaping and safety", () => {
  it("escapes donor names containing commas and quotes", async () => {
    const { renderTransactionCsv } = await loadModule();
    const row: any = {
      reportType: "", reportScope: "", reportOwnerName: "", reportOwnerEmail: "", reportOwnerUserId: "", reportOwnerRole: "",
      generatedByName: "", generatedByEmail: "", generatedAt: new Date(), periodStart: null, periodEnd: null, appliedFilters: "",
      organizationName: "", organizationId: "", teamMemberName: "", teamMemberEmail: "", givingLinkName: "", givingLinkId: "",
      wgcPaymentId: "p1", finixTransferId: "", createdAt: new Date(), currency: "USD", donorName: 'Smith, "Jane"', donorEmail: "",
      donorPhone: "", paymentMethod: "CARD", instrumentType: "", cardBrandOrBankType: "", lastFour: "", transactionStatus: "SUCCEEDED",
      refundStatus: "NONE", disputeStatus: "NONE", achReturnStatus: "NONE", donationAmountCents: 1000, donorProcessingFeeCents: 0,
      totalChargedToDonorCents: 1000, finixProcessingFeeCents: null, wgcSupplementalFeeCents: null, otherProcessorFeesCents: 0,
      totalFeesCents: null, refundAmountCents: 0, disputeAmountCents: 0, achReturnAmountCents: 0, expectedNetToOrganizationCents: null,
      actualNetToOrganizationCents: null, settlementIncluded: "NO", settlementAllocationAmountCents: null, settlementId: "",
      settlementStatus: "NOT_SETTLED", settlementCreatedAt: null, settlementProcessedAt: null, depositId: "", depositStatus: "",
      depositInitiatedAt: null, depositCompletedAt: null, destinationBankLastFour: "", traceId: "", reconciliationStatus: "NOT_SETTLED",
      dataNotes: "",
    };
    const csv = renderTransactionCsv([row]);
    expect(csv).toContain('"Smith, ""Jane"""');
  });
});
